window.PRODUCTS = [
    { title: 'Toalha de Banho Super Absorvente', img: 'https://down-br.img.susercontent.com/file/sg-11134301-7rces-lqxatznri20se2', video: '', link: 'https://s.shopee.com.br/qPfbip9uD', code: '4001' },
    { title: 'Toalha de Banho Toquio 140cm x 75cm 360gr/m² 100% Algodão', img: 'https://down-br.img.susercontent.com/file/9a693a61f1803d5151fd0220ffe3d43b', video: '', link: 'https://s.shopee.com.br/qPfc2YHRa', code: '4002' },
    /*{ title: '', img: '', video: '', link: '', code: '003' },
    { title: '', img: '', video: '', link: '', code: '004' },
    { title: '', img: '', video: '', link: '', code: '005' },
    { title: '', img: '', video: '', link: '', code: '006' },
    { title: '', img: '', video: '', link: '', code: '007' },
    { title: '', img: '', video: '', link: '', code: '008' },
    { title: '', img: '', video: '', link: '', code: '008' },
    { title: '', img: '', video: '', link: '', code: '009' },
    { title: '', img: '', video: '', link: '', code: '010' },
    { title: '', img: '', video: '', link: '', code: '011' },
    { title: '', img: '', video: '', link: '', code: '012' },
    { title: '', img: '', video: '', link: '', code: '013' },
    { title: '', img: '', video: '', link: '', code: '014' },
    { title: '', img: '', video: '', link: '', code: '015' },
    { title: '', img: '', video: '', link: '', code: '016' },
    { title: '', img: '', video: '', link: '', code: '017' },
    { title: '', img: '', video: '', link: '', code: '018' },
    { title: '', img: '', video: '', link: '', code: '019' },
    { title: '', img: '', video: '', link: '', code: '020' },
    { title: '', img: '', video: '', link: '', code: '021' },
    { title: '', img: '', video: '', link: '', code: '022' },
    { title: '', img: '', video: '', link: '', code: '023' },    
    { title: '', img: '', video: '', link: '', code: '024' },
    { title: '', img: '', video: '', link: '', code: '025' }*/
];

