window.PRODUCTS = [
    { title: 'Jaqueta Corta Vento', img: 'https://down-br.img.susercontent.com/file/sg-11134201-7rdwh-lxtkjb5s2h54d9', video: '', link: 'https://s.shopee.com.br/7zsq4Dmpgu', code: '7001' },
    { title: 'Calça Leggingn', img: 'https://down-br.img.susercontent.com/file/sg-11134201-7rd55-luqadgw17wq9e2', video: '', link: 'https://s.shopee.com.br/1fymXJNMDj', code: '7002' },
    { title: 'Luvas Ciclismo - Bike', img: '', video: 'https://cvf.shopee.com.br/file/42d1b3627599004099b42473fea69ec4', link: 'https://s.shopee.com.br/1B2VwmFqDB', code: '7003' },
    { title: 'Boné Suebra Sol', img: 'https://down-br.img.susercontent.com/file/cn-11134207-7r98o-lo27fkm0dxgba7', video: '', link: 'https://s.shopee.com.br/9f144uNkxz', code: '7004' },
    /*{ title: '', img: '', video: '', link: '', code: '005' },
    { title: '', img: '', video: '', link: '', code: '006' },
    { title: '', img: '', video: '', link: '', code: '007' },
    { title: '', img: '', video: '', link: '', code: '008' },
    { title: '', img: '', video: '', link: '', code: '008' },
    { title: '', img: '', video: '', link: '', code: '009' },
    { title: '', img: '', video: '', link: '', code: '010' },
    { title: '', img: '', video: '', link: '', code: '011' },
    { title: '', img: '', video: '', link: '', code: '012' },
    { title: '', img: '', video: '', link: '', code: '013' },
    { title: '', img: '', video: '', link: '', code: '014' },
    { title: '', img: '', video: '', link: '', code: '015' },
    { title: '', img: '', video: '', link: '', code: '016' },
    { title: '', img: '', video: '', link: '', code: '017' },
    { title: '', img: '', video: '', link: '', code: '018' },
    { title: '', img: '', video: '', link: '', code: '019' },
    { title: '', img: '', video: '', link: '', code: '020' },
    { title: '', img: '', video: '', link: '', code: '021' },
    { title: '', img: '', video: '', link: '', code: '022' },
    { title: '', img: '', video: '', link: '', code: '023' },    
    { title: '', img: '', video: '', link: '', code: '024' },
    { title: '', img: '', video: '', link: '', code: '025' }*/
];

