window.PRODUCTS = [
    { title: 'Teclado semimecânico para jogos', img: 'https://down-br.img.susercontent.com/file/br-11134207-7r98o-lv4tyus0nh5b9e', video: '', link: 'https://s.shopee.com.br/7zsdMeriZhttps://s.shopee.com.br/2VXtYmOqrX', code: '6001' },
    { title: 'Luminária Abajur', img: 'https://down-br.img.susercontent.com/file/br-11134207-7r98o-lw606kahfp1260', video: '', link: 'https://s.shopee.com.br/700Ivealts', code: '6002' },
    { title: 'Mouse Pad Gamer sem Fio', img: 'https://down-br.img.susercontent.com/file/br-11134207-7r98o-lsip3dgvrokkaf', video: '', link: 'https://s.shopee.com.br/8f8WvGPUYu', code: '6003' },
    { title: 'Mini IP Câmera Wifi sem fio visão noturna', img: 'https://down-br.img.susercontent.com/file/sg-11134201-7rcda-ltebmc1p4rqz65', video: '', link: 'https://s.shopee.com.br/50FEYtpoZd', code: '6004' },
    /*{ title: '', img: '', video: '', link: '', code: '005' },
    { title: '', img: '', video: '', link: '', code: '006' },
    { title: '', img: '', video: '', link: '', code: '007' },
    { title: '', img: '', video: '', link: '', code: '008' },
    { title: '', img: '', video: '', link: '', code: '008' },
    { title: '', img: '', video: '', link: '', code: '009' },
    { title: '', img: '', video: '', link: '', code: '010' },
    { title: '', img: '', video: '', link: '', code: '011' },
    { title: '', img: '', video: '', link: '', code: '012' },
    { title: '', img: '', video: '', link: '', code: '013' },
    { title: '', img: '', video: '', link: '', code: '014' },
    { title: '', img: '', video: '', link: '', code: '015' },
    { title: '', img: '', video: '', link: '', code: '016' },
    { title: '', img: '', video: '', link: '', code: '017' },
    { title: '', img: '', video: '', link: '', code: '018' },
    { title: '', img: '', video: '', link: '', code: '019' },
    { title: '', img: '', video: '', link: '', code: '020' },
    { title: '', img: '', video: '', link: '', code: '021' },
    { title: '', img: '', video: '', link: '', code: '022' },
    { title: '', img: '', video: '', link: '', code: '023' },    
    { title: '', img: '', video: '', link: '', code: '024' },
    { title: '', img: '', video: '', link: '', code: '025' }*/
];

