window.PRODUCTS = [
    { title: 'Garrafa de Água 800ml', img: '', video: 'https://cvf.shopee.com.br/file/api/v4/11110105/mms/br-11110105-6kfks-lw7j47inopleb7.16000081717697209.mp4', link: 'https://s.shopee.com.br/1qICfhK24K', code: '5001' },
    { title: 'Fone de ouvido Bluetooth', img: 'https://down-br.img.susercontent.com/file/sg-11134301-7rdx6-lxj53w2uiezk26', video: '', link: 'https://s.shopee.com.br/2Av35Uk7zG', code: '5002' },
    { title: 'Caixa de Som e Microfones', img: 'https://down-br.img.susercontent.com/file/br-11134207-7r98o-lum8q7tor9lx03', video: '', link: 'https://s.shopee.com.br/B9yipX2K0', code: '5003' },
    /*{ title: '', img: '', video: '', link: '', code: '004' },
    { title: '', img: '', video: '', link: '', code: '005' },
    { title: '', img: '', video: '', link: '', code: '006' },
    { title: '', img: '', video: '', link: '', code: '007' },
    { title: '', img: '', video: '', link: '', code: '008' },
    { title: '', img: '', video: '', link: '', code: '008' },
    { title: '', img: '', video: '', link: '', code: '009' },
    { title: '', img: '', video: '', link: '', code: '010' },
    { title: '', img: '', video: '', link: '', code: '011' },
    { title: '', img: '', video: '', link: '', code: '012' },
    { title: '', img: '', video: '', link: '', code: '013' },
    { title: '', img: '', video: '', link: '', code: '014' },
    { title: '', img: '', video: '', link: '', code: '015' },
    { title: '', img: '', video: '', link: '', code: '016' },
    { title: '', img: '', video: '', link: '', code: '017' },
    { title: '', img: '', video: '', link: '', code: '018' },
    { title: '', img: '', video: '', link: '', code: '019' },
    { title: '', img: '', video: '', link: '', code: '020' },
    { title: '', img: '', video: '', link: '', code: '021' },
    { title: '', img: '', video: '', link: '', code: '022' },
    { title: '', img: '', video: '', link: '', code: '023' },    
    { title: '', img: '', video: '', link: '', code: '024' },
    { title: '', img: '', video: '', link: '', code: '025' }*/
];

