window.PRODUCTS = [
    { title: 'Fonte Bebedouro Para Pets', img: '', video: 'https://cvf.shopee.com.br/file/api/v4/11110105/mms/br-11110105-6kfks-lub10aaznul0c4.16000081713550417.mp4', link: 'https://s.shopee.com.br/7UwMjvGzfm', code: '1001' },
    { title: 'Comedouro Pet', img: '', video: 'https://cvf.shopee.com.br/file/api/v4/11110105/mms/br-11110105-6kfkr-lrgc9r0802t76d.16000081707334310.mp4', link: 'https://s.shopee.com.br/4pvbaGeJVt', code: '1002' },
    { title: '', img: '', video: '', link: '', code: '003' },
    { title: '', img: '', video: '', link: '', code: '004' },
    { title: '', img: '', video: '', link: '', code: '005' },
    { title: '', img: '', video: '', link: '', code: '006' },
    { title: '', img: '', video: '', link: '', code: '007' },
    { title: '', img: '', video: '', link: '', code: '008' },
    { title: '', img: '', video: '', link: '', code: '008' },
    { title: '', img: '', video: '', link: '', code: '009' },
    { title: '', img: '', video: '', link: '', code: '010' },
    { title: '', img: '', video: '', link: '', code: '011' },
    { title: '', img: '', video: '', link: '', code: '012' },
    { title: '', img: '', video: '', link: '', code: '013' },
    { title: '', img: '', video: '', link: '', code: '014' },
    { title: '', img: '', video: '', link: '', code: '015' },
    { title: '', img: '', video: '', link: '', code: '016' },
    { title: '', img: '', video: '', link: '', code: '017' },
    { title: '', img: '', video: '', link: '', code: '018' },
    { title: '', img: '', video: '', link: '', code: '019' },
    { title: '', img: '', video: '', link: '', code: '020' },
    { title: '', img: '', video: '', link: '', code: '021' },
    { title: '', img: '', video: '', link: '', code: '022' },
    { title: '', img: '', video: '', link: '', code: '023' },    
    { title: '', img: '', video: '', link: '', code: '024' },
    { title: '', img: '', video: '', link: '', code: '025' }
];
