window.PRODUCTS = [
    { title: 'Ralador e Fatiador de Legumes', img: '', video: 'https://cvf.shopee.com.br/file/api/v4/11110105/mms/br-11110105-6kfkp-lnraads6s3lzf2.16000081699279907.mp4', link: 'https://s.shopee.com.br/7zsdMeriZ3', code: '2001' },
    { title: '', img: '', video: '', link: '', code: '002' },
    { title: '', img: '', video: '', link: '', code: '003' },
    { title: '', img: '', video: '', link: '', code: '004' },
    { title: '', img: '', video: '', link: '', code: '005' },
    { title: '', img: '', video: '', link: '', code: '006' },
    { title: '', img: '', video: '', link: '', code: '007' },
    { title: '', img: '', video: '', link: '', code: '008' },
    { title: '', img: '', video: '', link: '', code: '008' },
    { title: '', img: '', video: '', link: '', code: '009' },
    { title: '', img: '', video: '', link: '', code: '010' },
    { title: '', img: '', video: '', link: '', code: '011' },
    { title: '', img: '', video: '', link: '', code: '012' },
    { title: '', img: '', video: '', link: '', code: '013' },
    { title: '', img: '', video: '', link: '', code: '014' },
    { title: '', img: '', video: '', link: '', code: '015' },
    { title: '', img: '', video: '', link: '', code: '016' },
    { title: '', img: '', video: '', link: '', code: '017' },
    { title: '', img: '', video: '', link: '', code: '018' },
    { title: '', img: '', video: '', link: '', code: '019' },
    { title: '', img: '', video: '', link: '', code: '020' },
    { title: '', img: '', video: '', link: '', code: '021' },
    { title: '', img: '', video: '', link: '', code: '022' },
    { title: '', img: '', video: '', link: '', code: '023' },    
    { title: '', img: '', video: '', link: '', code: '024' },
    { title: '', img: '', video: '', link: '', code: '025' }
];

